name: PlayerRTP
version: '1.0'
main: me.workwolf.playerrtp.PlayerRTP
author: WorkWolf_2
api-version: '1.20'
commands:
  playertp:
    permission: "playertp.rtp"
    description: Teletrasporta uno staff alla posizione di un player casuale
